lab14/app/main/views.py
# app/main/views.py

import os

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from ..forms import UpdateAccountForm
from ..models import db

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.account'))
    else:
        return redirect(url_for('auth.login'))


@main_bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data

        if form.password.data:
            current_user.password = generate_password_hash(form.password.data)

        current_user.about_me = form.about_me.data

        if form.picture.data:
            _, file_extension = os.path.splitext(form.picture.data.filename)
            new_file_name = secure_filename(f"{current_user.id}.png")
            new_file_path = os.path.join('app/static/profile_images', new_file_name)
            form.picture.data.save(new_file_path)
            current_user.image_file = new_file_name

        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me

    return render_template('account.html', title='Account', form=form)

lab14/app/post/views.py
# app/posts/views.py
import datetime
import os

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from sqlalchemy import desc
from werkzeug.utils import secure_filename

from ..forms import PostForm
from ..models import db, Post, Category, Tag

posts_bp = Blueprint('posts', __name__)


@posts_bp.route('/posts', methods=['GET'])
def posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(desc(Post.created)).paginate(page=page, per_page=5, error_out=False)
    return render_template('posts/posts.html', posts=posts)


@posts_bp.route('/add_post', methods=['GET', 'POST'])
@login_required
def add_post():
    form = PostForm()
    categories = Category.query.all()
    form.category.choices = [(category.id, category.name) for category in categories]

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            text=form.text.data,
            user_id=current_user.id,
            category_id=form.category.data,
            type=form.type.data
        )

        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        post.tags.extend(tags)

        db.session.add(post)
        db.session.commit()

        if form.image.data:
            new_file_name = f"{post.id}.png"
            file_path = os.path.join('app/static/post_images', new_file_name)
            form.image.data.save(file_path)
            post.image = new_file_name

        db.session.commit()

        flash('Post created successfully!', 'success')
        return redirect(url_for('posts.posts'))

    return render_template('posts/add_post.html', form=form)


@posts_bp.route('/my_posts', methods=['GET'])
@login_required
def my_posts():
    page = request.args.get('page', 1, type=int)
    user_posts = Post.query.filter_by(user_id=current_user.id).order_by(desc(Post.created)).paginate(page=page, per_page=5, error_out=False)
    form = PostForm()
    return render_template('posts/my_posts.html', user_posts=user_posts, form=form)


@posts_bp.route('/edit_post/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    form = PostForm(obj=post)
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    post_tags = [tag.id for tag in post.tags]

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.type = form.type.data
        post.category_id = form.category.data
        post.created = datetime.datetime.utcnow()

        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        post.tags = tags

        if form.image.data:
            _, file_extension = os.path.splitext(form.image.data.filename)
            new_file_name = secure_filename(f"{post.id}.png")
            new_file_path = os.path.join('app/static/post_images', new_file_name)
            form.image.data.save(new_file_path)
            post.image = new_file_name

        db.session.commit()
        flash('Post updated successfully!', 'success')
        return redirect(url_for('posts.my_posts'))

    return render_template('posts/edit_posts.html', form=form, post=post)


@posts_bp.route('/delete_post/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if current_user.id != post.user_id:
        flash('You do not have permission to delete this post.', 'danger')
        return redirect(url_for('posts.my_posts'))

    db.session.delete(post)
    db.session.commit()

    flash('Post deleted successfully!', 'success')
    return redirect(url_for('posts.my_posts'))

lab14/app/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">

                    <h2 class="card-title">Account Information</h2>

                    <div class="user-info text-center">
                        {% if current_user.image_file %}
                        <div class="rounded-circle account-image-container text-center">
                            <img src="{{ url_for('static', filename='../static/profile_images/' + current_user.image_file) }}"
                                 alt="Profile Image" class="rounded-circle account-image img-fluid">
                        </div>
                        {% else %}
                        <div class="rounded-circle account-image img-fluid bg-light"></div>
                        {% endif %}
                        <p><strong>Username:</strong> {{ current_user.username }}</p>
                        <p><strong>Email:</strong> {{ current_user.email }}</p>
                    </div>

                    <p><strong>About Me:</strong> {{ current_user.about_me or 'Not provided' }}</p>
                    <p><strong>Last Seen:</strong> {{ current_user.last_seen.strftime('%Y-%m-%d %H:%M:%S') }}</p>

                </div>
            </div>
            <hr>

            <h4 class="card-title">Update Account</h4>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {{ form.username(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {{ form.email(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.about_me.label(class="form-control-label") }}
                    {{ form.about_me(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    <label for="profile_picture" class="form-control-label">Select Profile Picture:</label>
                    {{ form.picture(class="form-control-file", id="profile_picture") }}
                </div>

                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
<br><br>
{% endblock %}

lab14/app/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <style>
        body {
            background-color: #282c34;
            color: #61dafb;
            padding-top: 56px;
        }

        .navbar {
            background-color: #282c34;
            border-bottom: 1px solid #61dafb;
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            color: #61dafb;
        }

        .navbar-toggler-icon {
            background-color: #61dafb;
        }

        .text-center {
            margin-top: 20px;
        }

        .display-4 {
            color: #61dafb;
        }

        .container {
            background-color: #282c34;
            color: #61dafb;
            border: 1px solid #61dafb;
            border-radius: 5px;
            padding: 20px;
            margin-top: 20px;
        }

        .alert {
            margin-top: 20px;
        }

        .navbar-nav .nav-link {
            color: #61dafb;
        }

        .navbar-nav .nav-link:hover,
        .navbar-nav .nav-link:active {
            color: #fff;
        }
    </style>
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <nav class="navbar">
        <a class="navbar-brand">App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.add_post') }}">Make post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.posts') }}">Post feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.my_posts') }}">My posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('todos.todolist') }}">Todo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <br>

    <div class="text-center">
        {% if current_user.is_authenticated %}
        <p class="display-4">Hello, {{ current_user.username }}!</p>
        {% else %}
        <p class="display-4">Welcome, guest!</p>
        {% endif %}
    </div>

    <div class="container mt-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

lab14/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
<form method="POST" action="{{ url_for('auth.login') }}">

    {{ form.hidden_tag() }}

    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {{ form.email(class="form-control form-control-lg") }}
    </div>

    <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {{ form.password(class="form-control form-control-lg") }}
    </div>

    <div class="form-group">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
    </div>

    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info btn-lg") }}
    </div>

</form>
{% endblock %}

lab14/app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>
<form method="POST" action="{{ url_for('auth.register') }}">

    {{ form.hidden_tag() }}

    <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {{ form.username(class="form-control form-control-lg") }}
    </div>

    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {{ form.email(class="form-control form-control-lg") }}
    </div>

    <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {{ form.password(class="form-control form-control-lg") }}
    </div>

    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info btn-lg") }}
    </div>

</form>
{% endblock %}