lab14/app/todo/views.py
# app/todos/views.py

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

from ..forms import TodoForm
from ..models import db, Todo

todos_bp = Blueprint('todos', __name__)


@todos_bp.route('/todolist')
def todolist():
    if current_user.is_authenticated:
        todos = Todo.query.filter_by(user_id=current_user.id).all()
        return render_template('todos/index.html', todos=todos)
    else:
        return redirect(url_for('auth.login'))


@todos_bp.route('/addtodo', methods=['GET', 'POST'])
def add_todo():
    form = TodoForm()
    if form.validate_on_submit():
        todo = Todo(
            user_id=current_user.id,
            title=form.title.data,
            description=form.description.data,
            completed=form.completed.data
        )
        db.session.add(todo)
        db.session.commit()
        return redirect(url_for('todos.todolist'))
    return render_template('todos/add_todo.html', form=form)


@todos_bp.route('/edittodo/<int:id>', methods=['GET', 'POST'])
def edit_todo(id):
    todo = Todo.query.get_or_404(id)
    form = TodoForm(obj=todo)
    if form.validate_on_submit():
        todo.title = form.title.data
        todo.description = form.description.data
        todo.completed = form.completed.data
        db.session.commit()
        return redirect(url_for('todos.todolist'))
    return render_template('todos/edit_todo.html', form=form, todo=todo)


@todos_bp.route('/deletetodo/<int:id>')
def delete_todo(id):
    todo = Todo.query.get_or_404(id)
    db.session.delete(todo)
    db.session.commit()
    return redirect(url_for('todos.todolist'))

lab14/app/templates/todos/add_todo.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mt-4">Add Todo</h1>

    <form method="POST" action="{{ url_for('todos.add_todo') }}" class="mt-3">
        {{ form.hidden_tag() }}

        <div class="form-group">
            <label for="title">Title:</label>
            {{ form.title(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            {{ form.description(class="form-control") }}
        </div>

        {{ form.submit(class="btn btn-success") }}
    </form>
{% endblock %}

lab14/app/templates/todos/edit_todo.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mt-4">Edit Todo</h1>

    <form method="POST" action="{{ url_for('todos.edit_todo', id=todo.id) }}" class="mt-3">
        {{ form.hidden_tag() }}

        <div class="form-group">
            <label for="title">Title:</label>
            {{ form.title(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            {{ form.description(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="completed">Completed:</label>
            {{ form.completed(class="form-check-input ml-2") }}
        </div>

        {{ form.submit(class="btn btn-primary") }}
    </form>
{% endblock %}

lab14/app/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mt-4">Todo List</h1>
    <br>
    <ul class="list-group">
        {% for todo in todos %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between">
                    <div>
                        <h3 class="mb-1">{{ todo.title }}</h3>
                        <p class="mb-1">{{ todo.description }}</p>

                        {% if todo.completed %}
                            <p class="text-success">Completed: Yes</p>
                        {% else %}
                            <p class="text-danger">Completed: No</p>
                        {% endif %}
                    </div>

                    <div class="actions">
                        <a href="{{ url_for('todos.edit_todo', id=todo.id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <a href="{{ url_for('todos.delete_todo', id=todo.id) }}" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

    <a href="{{ url_for('todos.add_todo') }}" class="btn btn-primary mt-3">Add Todo</a>
{% endblock %}